"""Generate flat_roof.scad — OpenSCAD 3D model of double-shell concrete walls.

Models wall sections between openings, each as an outer boundary minus
its air-gap cavity.  Matches the wall section geometry from walls.svg.
All coordinates in feet.
"""
import os

from floorplan.gen_floorplan import build_floorplan_data
from floorplan.constants import WALL_OUTER, SHELL_THICKNESS, OPENING_INSIDE_RADIUS
from shared.wall_shells import enumerate_wall_sections, build_section_outlines

_DIR = os.path.dirname(os.path.abspath(__file__))
_OUT = os.path.join(_DIR, "flat_roof.scad")

WALL_HEIGHT_IN = 80.0  # inches
WALL_HEIGHT_FT = WALL_HEIGHT_IN / 12.0


def _scad_polygon(name: str, pts: list[tuple[float, float]]) -> str:
    """Return an OpenSCAD module wrapping a polygon."""
    lines = [f"// {len(pts)} vertices"]
    lines.append(f"module {name}() {{")
    lines.append("  polygon(points = [")
    for i, (e, n) in enumerate(pts):
        comma = "," if i < len(pts) - 1 else ""
        lines.append(f"    [{e:.6f}, {n:.6f}]{comma}")
    lines.append("  ]);")
    lines.append("}")
    return "\n".join(lines)


def generate():
    fp = build_floorplan_data()
    pts = fp.pts
    outline_segs = fp.outline_segs
    inner_segs = fp.inner_segs
    s_segs = fp.s_segs
    g_segs = fp.g_segs
    openings = fp.openings

    shell_t = SHELL_THICKNESS
    R_in = OPENING_INSIDE_RADIUS

    g_overrides = {7: fp.g_f8f9_poly}
    w_overrides = {7: fp.w_f8f9_poly}

    # Enumerate wall sections (O11-O1, O1-O2, O2-O3, ...)
    sections = enumerate_wall_sections(openings, outline_segs)
    # Rotate so O11-O1 comes first (matches walls.svg table order)
    sections = sections[-1:] + sections[:-1]

    # Build outer/cavity outlines for each section
    section_data = []
    for start_op, end_op in sections:
        outer_path, cavity_path = build_section_outlines(
            pts, outline_segs, inner_segs, s_segs, g_segs,
            start_op, end_op, shell_t, R_in, WALL_OUTER,
            g_seg_overrides=g_overrides, w_seg_overrides=w_overrides)
        label = f"{start_op.name}_{end_op.name}"
        section_data.append((label, outer_path, cavity_path))

    # --- Build OpenSCAD output ---
    out = []
    out.append("// flat_roof.scad — Double-shell concrete wall extrusion")
    out.append(f"// Wall height: {WALL_HEIGHT_IN:.0f}\" ({WALL_HEIGHT_FT:.4f} ft)")
    out.append("// Construction: 2\" outer shell / 4\" air gap / 2\" inner shell")
    out.append(f"// {len(section_data)} wall sections between openings")
    out.append("// Units: feet")
    out.append("// Generated by scad/gen_flat_roof.py")
    out.append("")
    out.append(f"wall_height = {WALL_HEIGHT_FT:.6f};")
    out.append("")

    # Per-section outer and cavity polygon modules
    for label, outer_path, cavity_path in section_data:
        out.append(f"// Wall section {label.replace('_', ' to ')}")
        out.append(_scad_polygon(f"wall_{label}_outer", outer_path))
        out.append("")
        out.append(_scad_polygon(f"wall_{label}_cavity", cavity_path))
        out.append("")

    # Assembly: union of all wall sections, each = outer minus cavity
    out.append("// --- Assembly ---")
    out.append("union() {")
    for label, _, _ in section_data:
        out.append(f"  linear_extrude(height = wall_height)")
        out.append(f"    difference() {{")
        out.append(f"      wall_{label}_outer();")
        out.append(f"      wall_{label}_cavity();")
        out.append(f"    }}")
    out.append("}")
    out.append("")

    with open(_OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {_OUT}")


if __name__ == "__main__":
    generate()
