"""Generate flat_roof.scad — OpenSCAD 3D model of concrete walls.

Extrudes the outer wall ring (outer outline minus inner wall outline)
straight up to 80" height.  All coordinates in feet to match the
floorplan coordinate system.
"""
import os

from shared.geometry import path_polygon
from floorplan.gen_floorplan import build_floorplan_data

_DIR = os.path.dirname(os.path.abspath(__file__))
_OUT = os.path.join(_DIR, "flat_roof.scad")

WALL_HEIGHT_IN = 80.0  # inches
WALL_HEIGHT_FT = WALL_HEIGHT_IN / 12.0


def _scad_polygon(name: str, pts: list[tuple[float, float]]) -> str:
    """Return an OpenSCAD polygon assignment as a string."""
    lines = [f"// {len(pts)} vertices"]
    lines.append(f"module {name}() {{")
    lines.append("  polygon(points = [")
    for i, (e, n) in enumerate(pts):
        comma = "," if i < len(pts) - 1 else ""
        lines.append(f"    [{e:.6f}, {n:.6f}]{comma}")
    lines.append("  ]);")
    lines.append("}")
    return "\n".join(lines)


def generate():
    fp = build_floorplan_data()
    outer_poly = fp.outer_poly
    inner_poly = fp.inner_poly

    out = []
    out.append("// flat_roof.scad — Concrete wall extrusion")
    out.append(f"// Wall height: {WALL_HEIGHT_IN:.0f}\" ({WALL_HEIGHT_FT:.4f} ft)")
    out.append("// Units: feet")
    out.append("// Generated by scad/gen_flat_roof.py")
    out.append("")
    out.append(f"wall_height = {WALL_HEIGHT_FT:.6f};")
    out.append("")

    out.append(_scad_polygon("outer_wall", outer_poly))
    out.append("")
    out.append(_scad_polygon("inner_wall", inner_poly))
    out.append("")

    out.append("// Concrete walls: outer outline minus inner wall, extruded up")
    out.append("linear_extrude(height = wall_height) {")
    out.append("  difference() {")
    out.append("    outer_wall();")
    out.append("    inner_wall();")
    out.append("  }")
    out.append("}")
    out.append("")

    with open(_OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {_OUT}")


if __name__ == "__main__":
    generate()
