"""Generate flat_roof.scad — OpenSCAD 3D model of double-shell concrete walls.

Models the two concrete shells (2" outer / 4" gap / 2" inner) with
openings O1–O11 cut through, extruded straight up to 80" height.
All coordinates in feet to match the floorplan coordinate system.
"""
import os

from shared.geometry import path_polygon
from floorplan.gen_floorplan import build_floorplan_data
from floorplan.openings import compute_outer_openings

_DIR = os.path.dirname(os.path.abspath(__file__))
_OUT = os.path.join(_DIR, "flat_roof.scad")

WALL_HEIGHT_IN = 80.0  # inches
WALL_HEIGHT_FT = WALL_HEIGHT_IN / 12.0


def _scad_polygon(name: str, pts: list[tuple[float, float]]) -> str:
    """Return an OpenSCAD module wrapping a polygon."""
    lines = [f"// {len(pts)} vertices"]
    lines.append(f"module {name}() {{")
    lines.append("  polygon(points = [")
    for i, (e, n) in enumerate(pts):
        comma = "," if i < len(pts) - 1 else ""
        lines.append(f"    [{e:.6f}, {n:.6f}]{comma}")
    lines.append("  ]);")
    lines.append("}")
    return "\n".join(lines)


def _apply_f8f9_override(poly, pts, prefix):
    """Replace the arc vertices between prefix8 and prefix9 with the
    straight-arc-straight polyline from fp.g_f8f9_poly / fp.w_f8f9_poly."""
    p8 = pts[f"{prefix}8"]
    p9 = pts[f"{prefix}9"]
    idx8 = next(i for i, p in enumerate(poly)
                if abs(p[0] - p8[0]) < 1e-9 and abs(p[1] - p8[1]) < 1e-9)
    idx9 = next(i for i, p in enumerate(poly)
                if i > idx8
                and abs(p[0] - p9[0]) < 1e-9 and abs(p[1] - p9[1]) < 1e-9)
    return idx8, idx9


def generate():
    fp = build_floorplan_data()

    # Four boundary polygons
    outer_poly = fp.outer_poly                       # F-series (exterior face)
    s_poly = path_polygon(fp.s_segs, fp.pts)         # S-series (2" inset)
    g_poly = list(path_polygon(fp.g_segs, fp.pts))   # G-series (6" inset)
    inner_poly = fp.inner_poly                       # W-series (8" inset, F8-F9 already fixed)

    # Apply G-series F8-F9 corner override
    g8 = fp.pts["G8"]
    g9 = fp.pts["G9"]
    g8_idx = next(i for i, p in enumerate(g_poly)
                  if abs(p[0] - g8[0]) < 1e-9 and abs(p[1] - g8[1]) < 1e-9)
    g9_idx = next(i for i, p in enumerate(g_poly)
                  if i > g8_idx
                  and abs(p[0] - g9[0]) < 1e-9 and abs(p[1] - g9[1]) < 1e-9)
    g_poly[g8_idx:g9_idx + 1] = fp.g_f8f9_poly

    # Openings (4-point polygons spanning F-face to W-face)
    outer_openings = compute_outer_openings(fp.pts, fp.layout)

    # --- Build OpenSCAD output ---
    out = []
    out.append("// flat_roof.scad — Double-shell concrete wall extrusion")
    out.append(f"// Wall height: {WALL_HEIGHT_IN:.0f}\" ({WALL_HEIGHT_FT:.4f} ft)")
    out.append("// Construction: 2\" outer shell / 4\" air gap / 2\" inner shell")
    out.append("// Units: feet")
    out.append("// Generated by scad/gen_flat_roof.py")
    out.append("")
    out.append(f"wall_height = {WALL_HEIGHT_FT:.6f};")
    out.append("")

    # Polygon modules for the four boundaries
    out.append("// --- Boundary polygons ---")
    out.append(_scad_polygon("outer_wall", outer_poly))
    out.append("")
    out.append(_scad_polygon("s_boundary", s_poly))
    out.append("")
    out.append(_scad_polygon("g_boundary", g_poly))
    out.append("")
    out.append(_scad_polygon("inner_wall", inner_poly))
    out.append("")

    # Shell modules
    out.append("// --- Shell modules ---")
    out.append("module outer_shell() {")
    out.append("  difference() {")
    out.append("    outer_wall();")
    out.append("    s_boundary();")
    out.append("  }")
    out.append("}")
    out.append("")
    out.append("module inner_shell() {")
    out.append("  difference() {")
    out.append("    g_boundary();")
    out.append("    inner_wall();")
    out.append("  }")
    out.append("}")
    out.append("")

    # Opening modules
    out.append("// --- Opening cutouts ---")
    for op in outer_openings:
        out.append(_scad_polygon(f"opening_{op.name}", op.poly))
        out.append("")

    # Final assembly
    out.append("// --- Assembly: shells with openings cut through ---")
    out.append("difference() {")
    out.append("  linear_extrude(height = wall_height) {")
    out.append("    outer_shell();")
    out.append("    inner_shell();")
    out.append("  }")
    for op in outer_openings:
        out.append(f"  linear_extrude(height = wall_height) opening_{op.name}();")
    out.append("}")
    out.append("")

    with open(_OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {_OUT}")


if __name__ == "__main__":
    generate()
